backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "source/assets/images"
public_folder: "assets/images"
collections:
  - name: "Post"
    label: "Post"
    folder: "source/_posts"
    create: true
    slug: {{slug}}
    fields:
      - {label: "Extends", name: "extends", widget: "hidden", default: "_layouts.blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
